---
# Add the user for logging in with

- name: "Add groups"
  become: true
  ansible.builtin.group:
    name: "{{ item }}"
  loop:
  - "{{ vm_user }}"
  - sudo

- name: "Add user with password: {{ vm_user }}"
  become: true
  ansible.builtin.user:
    name: "{{ vm_user }}"
    groups:
    - "{{ vm_user }}"
    - sudo
    shell: /bin/bash
    password: "{{ vm_password | string | password_hash('sha512', 'quantummobile') }}"
    update_password: on_create

- name: "Enable passwordless sudo for group {{ vm_user }}"
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%{{ vm_user }}'
    line: '%{{ vm_user }} ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add user to 'vboxsf' group on VirtualBox
  # This enables sudoless access to shared folder in VirtualBox
  when: cloud_platform == 'virtualbox'
  become: true
  ansible.builtin.user:
    name: "{{ vm_user }}"
    groups: vboxsf
    append: true
