---
- name: "Check if conda env exists: '{{ conda_env }}'"
  become: true
  become_user: "{{ vm_user }}"
  ansible.builtin.stat:
    path: "/home/{{ vm_user }}/.conda/envs/{{ conda_env }}"
  register: conda_env_stat

- name: "Install environment: {{ conda_env }} "
  become: true
  become_user: "{{ vm_user }}"
  ansible.builtin.shell: >
    ~/.conda/bin/mamba {{ 'install' if conda_env_stat.stat.exists else 'create' }}
    -n {{ conda_env }} -y {{ packages | join(' ') }}
  register: result
  changed_when: "'All requested packages already installed' not in result.stdout"

- name: "Symlink binaries to ~/.local/bin: {{ conda_env }}"
  become: true
  become_user: "{{ vm_user }}"
  when: bin_patterns is defined and bin_patterns | length > 0
  block:
  - name: "Create ~/.local/bin"
    ansible.builtin.file:
      path: "/home/{{ vm_user }}/.local/bin"
      state: directory
      mode: "0755"
  - name: "Add ~/.local/bin to PATH in .bashrc"
    ansible.builtin.blockinfile:
      path: "/home/{{ vm_user }}/.bashrc"
      marker: "## {mark} ANSIBLE MANAGED BLOCK (~/.local/bin)"
      block: |
        export PATH="$HOME/.local/bin:$PATH"
  - name: "Find binaries matching patterns"
    ansible.builtin.find:
      paths: "/home/{{ vm_user }}/.conda/envs/{{ conda_env }}/bin"
      patterns: "{{ bin_patterns }}"
      file_type: any
    register: found_binaries
  - name: "Create symlinks"
    ansible.builtin.file:
      src: "{{ binary.path }}"
      dest: "/home/{{ vm_user }}/.local/bin/{{ binary.path | basename }}"
      state: link
    loop: "{{ found_binaries.files }}"
    loop_control:
      loop_var: binary
      label: "{{ binary.path | basename }}"

- name: "Retrieve list of core packages in env: {{ conda_env }}"
  become: true
  become_user: "{{ vm_user }}"
  chrisjsewell.conda.list_pkgs:
    executable: "~/.conda/bin/mamba"
    env: "{{ conda_env }}"
    regex: "({{ packages | map('regex_search', '^[^=]+') | join('|') }})"
  register: packages_list

- name: Document conda packages in release notes
  ansible.builtin.include_role:
    name: release_notes
    public: true
  vars:
    section: "Conda '{{ conda_env }}' environment"
    option: "{{ pkg.name }}"
    value: "{{ pkg.version }}-{{ pkg.build_string }}@{{ pkg.channel }}"
  loop: "{{ packages_list.list }}"
  loop_control:
    loop_var: pkg
    label: "{{ pkg.name }}"
  when: release_notes is defined and release_notes
