---
# Run as user

- name: Create folder for images
  become: true
  become_user: "{{ root_user }}"
  ansible.builtin.file:
    path: "{{ vm_data_folder }}/qm-customizations"
    state: directory
    mode: "0755"

- name: Copy the background image
  become: true
  become_user: "{{ root_user }}"
  ansible.builtin.copy:
    src: images/quantum-mobile-bg.png
    dest: "{{ vm_data_folder }}/qm-customizations/quantum-mobile-bg.png"
    mode: "0755"

- name: Set wallpaper
  # Note: This is applied immediately, no restart needed
  community.general.dconf:
    key: /org/gnome/desktop/background/picture-uri
    value: "'file://{{ vm_data_folder }}/qm-customizations/quantum-mobile-bg.png'"
    state: present

- name: Copy quamtum-mobile logo
  become: true
  become_user: "{{ root_user }}"
  ansible.builtin.copy:
    src: images/quantum-mobile-logo.png
    dest: /usr/share/icons/
    mode: "0644"

- name: Create desktop if not exists
  ansible.builtin.file:
    path: "${HOME}/Desktop"
    state: directory
    mode: "0755"
