---
- name: Build base Quantum Mobile layer
  ansible.builtin.import_playbook: playbook-build-base.yml

- name: Install QE School workshop software
  hosts: "{{ build_hosts | default('vagrant') }}"

  tasks:
  - name: Install Koopmans toolchain
    tags: [koopmans]
    become: true
    become_user: "{{ vm_user }}"
    ansible.builtin.import_tasks: qe-school/tasks/koopmans.yml

  - name: Install metatomic conda environment
    tags: [metatomic]
    become: true
    become_user: "{{ vm_user }}"
    ansible.builtin.import_tasks: qe-school/tasks/metatomic.yml

  - name: Install qe conda environment
    tags: [qe]
    become: true
    become_user: "{{ vm_user }}"
    ansible.builtin.import_tasks: qe-school/tasks/qe.yml

  - name: Install wannier conda environment
    tags: [wannier]
    become: true
    become_user: "{{ vm_user }}"
    ansible.builtin.import_tasks: qe-school/tasks/wannier.yml

  - name: Install yambo conda environment
    tags: [yambo]
    become: true
    become_user: "{{ vm_user }}"
    ansible.builtin.import_tasks: qe-school/tasks/yambo.yml
