---
# Needed to modify this role for become_user
# See https://github.com/marvel-nccr/quantum-mobile/issues/67
#- src: gantsign.default-web-browser
#  version: 3.1.0
- src: marvel-nccr.ansible_prerequisites
  version: v0.1.0
- src: marvel-nccr.current_user
  version: v0.1.0
- src: marvel-nccr.add_user
  version: v0.2.1
- src: marvel-nccr.simulationbase
  version: v0.1.1
- src: marvel-nccr.ubuntu_desktop
  version: v0.1.0
- src: marvel-nccr.quantum_mobile_customizations
  version: v0.1.0
- src: marvel-nccr.editors
  version: v0.1.0
- src: marvel-nccr.slurm
  version: v0.1.1
- src: marvel-nccr.quantum_espresso
  version: v0.1.0
- src: marvel-nccr.yambo
  version: v0.1.0
- src: marvel-nccr.fleur
  version: v0.1.0
- src: marvel-nccr.siesta
  version: v0.1.0
- src: marvel-nccr.cp2k
  version: v0.1.0
- src: marvel-nccr.wannier90
  version: v0.1.0
#- src: marvel-nccr.aiida
#  version: v0.1.0
- src: https://github.com/marvel-nccr/ansible-role-aiida.git
  version: tutorial-2019-05
  name: marvel-nccr.aiida
#- src: marvel-nccr.aiidalab
#  version: v0.1.0
- src: https://github.com/marvel-nccr/ansible-role-aiidalab.git
  version: tutorial-2019-05
  name: marvel-nccr.aiidalab
