---
# Needed to modify this role for become_user
# See https://github.com/marvel-nccr/quantum-mobile/issues/67
#- src: gantsign.default-web-browser
#  version: 3.1.0
- src: marvel-nccr.ansible_prerequisites
  version: master
- src: marvel-nccr.current_user
  version: master
- src: marvel-nccr.add_user
  version: master
- src: marvel-nccr.simulationbase
  version: master
- src: marvel-nccr.ubuntu_desktop
  version: master
- src: marvel-nccr.quantum_mobile_customizations
  version: master
- src: marvel-nccr.editors
  version: master
- src: marvel-nccr.slurm
  version: master
- src: marvel-nccr.quantum_espresso
  version: master
- src: marvel-nccr.yambo
  version: master
- src: marvel-nccr.fleur
  version: master
- src: marvel-nccr.siesta
  version: master
- src: marvel-nccr.cp2k
  version: master
- src: marvel-nccr.wannier90
  version: master
- src: marvel-nccr.aiida
  version: master
- src: marvel-nccr.aiidalab
  version: master
