---
collections:
- name: chrisjsewell.conda
  version: 0.0.9
- name: community.postgresql
  version: ">=3.0.0"
- name: ansible.posix
  version: ">=1.5.0"
roles:
- name: gantsign.default-web-browser
  version: 4.0.0
- name: marvel-nccr.current_user
  version: v0.1.0
- name: marvel-nccr.add_user
  version: v0.2.1
- name: marvel-nccr.ubuntu_desktop
  version: v2.0.0
- name: marvel-nccr.editors
  version: v1.0.2
- name: marvel-nccr.slurm
  version: v3.0.0
