- src: gantsign.default-web-browser
  version: 3.2.0
- src: marvel-nccr.current_user
  version: v0.1.0
- src: marvel-nccr.add_user
  version: v0.2.1
- src: marvel-nccr.ubuntu_desktop
  version: v1.0.4
- src: marvel-nccr.quantum_mobile_customizations
  version: v1.1.1
- src: marvel-nccr.editors
  version: v1.0.2
- src: marvel-nccr.slurm
  version: v2.0.2
- src: marvel-nccr.aiida_cws
  version: v0.0.6
