---
- src: marvel-nccr.quantum-espresso
  version: master
- src: marvel-nccr.fleur
  version: master
- src: marvel-nccr.cp2k
  version: master
- src: marvel-nccr.wannier90
  version: master
- src: marvel-nccr.siesta
  version: master
- src: marvel-nccr.yambo
  version: master
- src: marvel-nccr.editors
  version: master
- src: marvel-nccr.simulationbase
  version: master
- src: marvel-nccr.ubuntu-desktop
  version: master
- src: marvel-nccr.quantum-mobile-customizations
  version: master
- src: marvel-nccr.add-user
  version: master
- src: marvel-nccr.torque
  version: master
- src: marvel-nccr.aiida
  version: master
- src: marvel-nccr.current-user
  version: master
