---
- src: gantsign.default-web-browser
  version: 3.2.0
- src: marvel-nccr.ansible_prerequisites
  version: v0.1.0
- src: marvel-nccr.current_user
  version: v0.1.0
- src: marvel-nccr.add_user
  version: v0.2.1
- src: marvel-nccr.simulationbase
  version: v1.0.5
- src: marvel-nccr.ubuntu_desktop
  version: v1.0.1
- src: marvel-nccr.quantum_mobile_customizations
  version: v1.0.4
- src: marvel-nccr.editors
  version: v1.0.1
- src: marvel-nccr.slurm
  version: v1.0.0
- src: marvel-nccr.quantum_espresso
  version: v1.1.2
- src: marvel-nccr.yambo
  version: v1.0.2
- src: marvel-nccr.fleur
  version: v1.0.2
- src: marvel-nccr.siesta
  version: v1.0.1
- src: marvel-nccr.cp2k
  version: v1.0.1
- src: marvel-nccr.bigdft
  version: v1.0.0
- src: marvel-nccr.wannier90
  version: v1.0.0
- src: marvel-nccr.aiida
  version: v1.0.1
#- src: https://github.com/marvel-nccr/ansible-role-aiida.git
#  version: develop
#  name: marvel-nccr.aiida
- src: marvel-nccr.aiidalab
  version: v1.0.1
