# may roles require installing from apt or pip
# here we ensure both are available and up-to-date

- name: Update apt cache and install aptitude
  become: true
  become_user: "{{ root_user }}"
  apt:
    name:
    - aptitude
    - python3-pip
    update_cache: true
    cache_valid_time: 86400  # One day

- name: Create man directory
  when: cloud_platform == 'docker'
  file:
    path: /usr/share/man/man1
    state: directory

- name: upgrade pip
  become: true
  become_user: "{{ root_user }}"
  pip:
    name: pip
    extra_args: --upgrade
