- name: Install plotting tools, etc.
  become: true
  become_user: "{{ root_user }}"
  apt:
    name: "{{ packages }}"
    state: present

- include_role:
    name: release_notes
  vars:
    section: "Plotting Tools"
    option: "available tools"
    value: "{{ packages | join(', ') }}"
  when: release_notes is defined and release_notes
