# these are general setups needed by many simulation codes

- name: Create a /scratch directory for calculations
  become: true
  become_user: "{{ root_user }}"
  file:
    path: "/scratch"
    state: directory
    mode: 0777

- name: set timezone to {{ vm_timezone }}
  when: cloud_platform != 'docker'
  become: true
  timezone:
    name: "{{ vm_timezone }}"
  tags: simulationbase_timezone

- name: set stack size to unlimited
  become: true
  become_user: "{{ vm_user }}"
  lineinfile:
    path: "${HOME}/.profile"
    line: ulimit -s unlimited

- name: "Check if swapfile exists"
  stat: path=/swapfile
  register: swapfile_stat

- when: (not swapfile_stat.stat.exists) and cloud_platform != 'docker'
  become: true
  become_user: "{{ root_user }}"
  block:

  # a swap file allows the system to use the hard disk as virtual memory
  # this is useful if the system has less than 4GB of RAM,
  # although it does make the system slower

  - name: "Create swapfile"
    command: "dd if=/dev/zero of=/swapfile bs=1M count=1024"

  - name: "Make the swapfile a valid swap"
    command: "mkswap /swapfile"

  - name: "Use the swapfile"
    command: "swapon /swapfile"

  - name: "Put a line in fstab to ensure swap is used at boot time"
    lineinfile:
      path: "/etc/fstab"
      line: "/swapfile swap swap defaults 0 0"
