#!/usr/bin/env python3

from jupyterhub import singleuser

# https://github.com/jupyterhub/jupyterhub/blob/master/scripts/jupyterhub-singleuser
# https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/singleuser.py

matcloud_page_template = """
{% extends "templates/page.html" %}
{% block header_buttons %}
{{super()}}
<span>
    <a href='{{hub_control_panel_url}}'
       class='btn btn-default btn-sm navbar-btn pull-right'
       style='margin-right: 4px; margin-left: 2px;'>
        Control Panel
    </a>
</span>
<span>
    <a href='http://test-dev.materialscloud.org/home'
       class='btn btn-default btn-sm navbar-btn pull-right'
       style='margin-right: 4px; margin-left: 2px;'>
        Materials Cloud
    </a>
</span>
{% endblock %}
{% block logo %}
<img src='{{logo_url}}' alt='Jupyter Notebook'/>
{% endblock logo %}
"""

if __name__ == '__main__':
    singleuser.page_template = matcloud_page_template
    singleuser.main()
