- name: "get the machine hostname"
  become: true
  shell: "hostname"
  register: cur_hostname_command
  changed_when: False

  # This updates both the current hostname and /etc/hostname
- name: "update machine hostname, if necessary"
  become: true
  shell: "hostnamectl set-hostname {{ globalconfig.vm_hostname }}"
  when: cur_hostname_command.stdout != globalconfig.vm_hostname

- name: "remove any lines with 127.0.1.1"
  become: true
  lineinfile: 
    path: "/etc/hosts"
    regexp: '^127\.0\.1\.1'
    state: absent
    owner: root
    group: root
    mode: 0644

- name: "set 127.0.1.1 to localhost (if it's set to the hostname, pbs server complains)"
  become: true
  lineinfile: 
    path: "/etc/hosts"
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 localhost"
    owner: root
    group: root
    mode: 0644

- name: "set hostname for dynamic ip address in /etc/hosts (needed for PBS Torque)"
  become: true
  lineinfile: 
    path: "/etc/hosts"
    regexp: "{{ globalconfig.vm_hostname }}$"
    line: "{{ ansible_default_ipv4.address }} {{ globalconfig.vm_hostname }}"
    owner: root
    group: root
    mode: 0644
