collections:
- name: chrisjsewell.conda
  version: 0.0.8
roles:
- name: gantsign.default-web-browser
  version: 3.2.0
- name: geerlingguy.nodejs
  version: 5.1.1
- name: marvel-nccr.current_user
  version: v0.1.0
- name: marvel-nccr.add_user
  version: v0.2.1
- name: marvel-nccr.python
  version: v0.2.2
- name: marvel-nccr.ubuntu_desktop
  version: v1.0.4
- name: marvel-nccr.editors
  version: v1.0.2
- name: marvel-nccr.slurm
  version: v2.0.2
- name: marvel-nccr.libxc
  version: v0.1.0
- name: marvel-nccr.abinit
  version: v2.1.1
- name: marvel-nccr.nwchem
  version: v0.0.4
- name: marvel-nccr.quantum_espresso
  version: v1.3.1
- name: marvel-nccr.yambo
  version: v1.2.0
- name: marvel-nccr.fleur
  version: v1.1.0
- name: marvel-nccr.siesta
  version: v2.2.1
- name: marvel-nccr.cp2k
  version: v1.2.0
- name: marvel-nccr.bigdft
  version: v1.4.0
- name: marvel-nccr.wannier90
  version: v1.1.4
- name: marvel-nccr.wannier_tools
  version: v1.0.0
- name: marvel-nccr.aiida
  version: v5.0.0
