#!/bin/sh
### BEGIN INIT INFO
# Provides:          fix-hostname
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# X-Start-Before:    torque-server torque-mom torque-scheduler
# X-Start-After:    torque-server torque-mom torque-scheduler
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Force hostname
# Description:       Force hostname to {{ vm_hostname }}
### END INIT INFO

# We set the hostname irregardless of $1, i.e. even if this script is called
# with a parameter 'start' or 'stop'
HOSTNAME={{ vm_hostname }}
hostname $HOSTNAME
echo $HOSTNAME > /etc/hostname
